version: '3.9'
services:
    warp-socks:
        image: monius/docker-warp-socks:latest
        ports:
            - "9091:9091"
        privileged: true
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        volumes:
            - /lib/modules:/lib/modules
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0
            net.ipv4.conf.all.src_valid_mark: 1
    test:
        image: curlimages/curl
        network_mode: host
        depends_on:
            - warp-socks
        command: curl --proxy socks5h://127.0.0.1:9091 https://www.cloudflare.com/cdn-cgi/trace 
