name: test

on:
  workflow_run:
    workflows: ["pub"]
    types:
      - completed

jobs:
  testx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            cpu: cortex-a53
            base_image: raspios_lite_arm64:latest
            cpu_info: raspberrypi_zero2_w_arm64_w
    steps:
    - uses: pguyot/arm-runner-action@v2
      name: Test release on RPI
      with:
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        commands: |
            apt-get update -q -y
            apt-get install -q -y git curl sudo gnupg ca-certificates software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            add-apt-repository "$(dpkg --print-architecture) https://download.docker.com/linux/ubuntu focal stable"
            apt-get update -q -y && apt-get install -q -y docker-ce
            echo ::set-output name=uname::$(uname -a)

    - name: Check proxy status
      run: |
        echo "The uname output was ${{ steps.test.outputs.uname }}"
        apt-get update -q -y
        apt-get install -q -y curl
        curl --proxy socks5h://127.0.0.1:9091 https://www.cloudflare.com/cdn-cgi/trace