name: test

on:
  workflow_run:
    workflows: ["pub"]
    types:
      - completed

jobs:
  testx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - 
        run: |
          set -x

          docker version

          docker run --privileged --restart=always -itd \
              --name warp_socks \
              --sysctl net.ipv6.conf.all.disable_ipv6=0 \
              --sysctl net.ipv4.conf.all.src_valid_mark=1 \
              --cap-add NET_ADMIN --cap-add SYS_MODULE \
              -p 9091:9091 \
              -v /lib/modules:/lib/modules \
              monius/docker-warp-socks

      - name: Check proxy status
        id: check
        run: |
          set -x
          curl --version
          curl --proxy "socks5h://127.0.0.1:9091" "https://www.cloudflare.com/cdn-cgi/trace" > 1.txt
          curl "https://www.cloudflare.com/cdn-cgi/trace"
          echo ::set-output name=trace::yes
      - name: Show proxy status
        run: |
          echo "The proxy status is ${{ steps.check.outputs.trace }}"
      - 
        name: Debug Mode
        uses: lhotari/action-upterm@v1
        if: ${{ steps.check.outputs.trace != 'warp=on' }}