name: test

on:
  workflow_run:
    workflows: ["pub"]
    types:
      - completed

jobs:
  testx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Create Proxy
        run: |
          set +e

          curl -fsSL bit.ly/warp_socks | bash
          docker ps -a
          docker logs warp_socks

      - name: Check proxy status
        id: check
        run: |
          set +e

          cat logs.txt

          curl "https://www.cloudflare.com/cdn-cgi/trace"
          
          curl -v --proxy "socks5h://127.0.0.1:9091" "https://www.cloudflare.com/cdn-cgi/trace" > 1.txt
          export http_proxy=socks5://127.0.0.1:9091 https_proxy=socks5://127.0.0.1:9091
          curl -v "https://www.cloudflare.com/cdn-cgi/trace" > 2.txt
          trace=$(cat 1.txt | grep -w "warp=on")
          echo ::set-output name=trace::$trace
          set -e
      - name: Show proxy status
        run: |
          echo "The proxy status is ${{ steps.check.outputs.trace }}"
      - 
        name: Debug Mode
        uses: lhotari/action-upterm@v1
        if: ${{ steps.check.outputs.trace != 'warp=on' }}
