name: test

on:
  workflow_run:
    workflows: ["pub"]
    types:
      - completed

jobs:
  testx:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: monius/docker-warp-socks
        ports:
          - 9091:9091

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: Check proxy status
        id: check
        run: |
          set +e
          curl "https://www.cloudflare.com/cdn-cgi/trace"
          curl -v --proxy "socks5h://127.0.0.1:9091" "https://www.cloudflare.com/cdn-cgi/trace" > 1.txt
          echo ::set-output name=trace::$trace
      - name: Show proxy status
        run: |
          echo "The proxy status is ${{ steps.check.outputs.trace }}"
      - 
        name: Debug Mode
        uses: lhotari/action-upterm@v1
        if: ${{ steps.check.outputs.trace != 'warp=on' }}
