name: test

on:
  workflow_run:
    workflows: ["pub"]
    types:
      - completed

jobs:
  testx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Docker Setup
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt -y update && sudo apt -y install docker-ce
      -
        name: Create Proxy
        run: |
          sudo docker run --privileged --restart=always -itd \
              --name warp_socks --env LOG=1 \
              --sysctl net.ipv6.conf.all.disable_ipv6=0 \
              --sysctl net.ipv4.conf.all.src_valid_mark=1 \
              --cap-add NET_ADMIN --cap-add SYS_MODULE \
              -p 9091:9091 \
              -v /lib/modules:/lib/modules \
              monius/docker-warp-socks

          sudo docker log warp_socks

      - name: Check proxy status
        id: check
        run: |
          set +e

          curl "https://www.cloudflare.com/cdn-cgi/trace"
          
          curl -v --proxy "socks5h://127.0.0.1:9091" "https://www.cloudflare.com/cdn-cgi/trace" > 1.txt
          export http_proxy=socks5://127.0.0.1:9091 https_proxy=socks5://127.0.0.1:9091
          curl -v "https://www.cloudflare.com/cdn-cgi/trace" > 2.txt
          trace=$(cat 1.txt | grep -w "warp=on")
          echo ::set-output name=trace::$trace
          set -e
      - name: Show proxy status
        run: |
          echo "The proxy status is ${{ steps.check.outputs.trace }}"
      - 
        name: Debug Mode
        uses: lhotari/action-upterm@v1
        if: ${{ steps.check.outputs.trace != 'warp=on' }}
