name: test

on:
  workflow_run:
    workflows: ["pub"]
    types:
      - completed

jobs:
  testx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Debug Mode
        uses: lhotari/action-upterm@v1
      - 
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - 
        run: |
          set -x

          sudo touch /continue

          docker version

          docker run --privileged --restart=always -itd \
              --name warp_socks \
              --sysctl net.ipv6.conf.all.disable_ipv6=0 \
              --sysctl net.ipv4.conf.all.src_valid_mark=1 \
              --cap-add NET_ADMIN --cap-add SYS_MODULE \
              -p 9091:9091 \
              -v /lib/modules:/lib/modules \
              monius/docker-warp-socks
          

      - name: Check proxy status
        run: |
          set -x
          curl --version
          curl https://www.cloudflare.com/cdn-cgi/trace
          
          