name: test

on:
  workflow_run:
    workflows: ["pub"]
    types:
      - completed

jobs:
  testx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Create Proxy
        shell: bash
        run: |
          curl -fsSL bit.ly/warp_socks | bash
          docker ps -a
          docker logs warp_socks

      - name: Check proxy status
        shell: bash
        id: check
        run: |
          set +e
          trace=$(curl -v --proxy "socks5h://127.0.0.1:9091" "https://www.cloudflare.com/cdn-cgi/trace" | grep -w "warp=on")
          echo ::set-output name=trace::$trace
      - name: Show proxy status
        shell: bash
        run: |
          echo "The proxy status is ${{ steps.check.outputs.trace }}"
      - 
        name: Debug Mode
        uses: lhotari/action-upterm@v1
        if: ${{ steps.check.outputs.trace != 'warp=on' }}
